y='\n            By default, after a dependency is called the first time in a request, if\n            the dependency is declared again for the rest of the request (for example\n            if the dependency is needed by several dependencies), the value will be\n            re-used for the rest of the request.\n\n            Set `use_cache` to `False` to disable this behavior and ensure the\n            dependency is called again (if declared more than once) in the same request.\n            '
x='\n            A "dependable" callable (like a function).\n\n            Don\'t call it directly, FastAPI will call it for you, just pass the object\n            directly.\n            '
w="\n            The media type of this parameter field. Changing it would affect the\n            generated OpenAPI, but currently it doesn't affect the parsing of the data.\n            "
v='\n            Default value if the parameter field is not set.\n            '
u='\n            The `extra` kwargs is deprecated. Use `json_schema_extra` instead.\n            '
t='\n            Include extra fields used by the JSON Schema.\n            '
s='\n            Any additional JSON schema data.\n            '
r="\n            To include (or not) this parameter field in the generated OpenAPI.\n            You probably don't need it, but it's available.\n\n            This affects the generated OpenAPI (e.g. visible at `/docs`).\n            "
q='\n            Mark this parameter field as deprecated.\n\n            It will affect the generated OpenAPI (e.g. visible at `/docs`).\n            '
p="\n            OpenAPI-specific examples.\n\n            It will be added to the generated OpenAPI (e.g. visible at `/docs`).\n\n            Swagger UI (that provides the `/docs` interface) has better support for the\n            OpenAPI-specific examples than the JSON Schema `examples`, that's the main\n            use case for this.\n\n            Read more about it in the\n            [FastAPI docs for Declare Request Example Data](https://fastapi.tiangolo.com/tutorial/schema-extra-example/#using-the-openapi_examples-parameter).\n            "
o='Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, although still supported. Use examples instead.'
n='\n            Example values for this field.\n            '
m='\n            Maximum number of decimal places allowed for numbers.\n            '
l='\n            Maximum number of allow digits for strings.\n            '
k='\n            Allow `inf`, `-inf`, `nan`. Only applicable to numbers.\n            '
j='\n            Value must be a multiple of this. Only applicable to numbers.\n            '
i='\n            If `True`, strict validation is applied to the field.\n            '
h='\n            Parameter field name for discriminating the type in a tagged union.\n            '
g='Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead.'
f='\n            Maximum length for strings.\n            '
e='\n            Minimum length for strings.\n            '
d='\n            Less than or equal. If set, value must be less than or equal to this.\n            Only applicable to numbers.\n            '
c='\n            Less than. If set, value must be less than this. Only applicable to numbers.\n            '
b='\n            Greater than or equal. If set, value must be greater than or equal to\n            this. Only applicable to numbers.\n            '
a='\n            Greater than. If set, value must be greater than this. Only applicable to\n            numbers.\n            '
Z='\n            Human-readable description.\n            '
Y='\n            Human-readable title.\n            '
X="\n            'Blacklist' validation step. The vanilla parameter field will be the\n            single one of the alias' or set of aliases' fields and all the other\n            fields will be ignored at serialization time.\n            "
W="\n            'Whitelist' validation step. The parameter field will be the single one\n            allowed by the alias or set of aliases defined.\n            "
V='\n            Priority of the alias. This affects whether an alias generator is used.\n            '
U="\n            An alternative name for the parameter field.\n\n            This will be used to extract the data and for the generated OpenAPI.\n            It is particularly useful when you can't use the name you want because it\n            is a Python reserved keyword or similar.\n            "
T="\n            A callable to generate the default value.\n\n            This doesn't affect `Path` parameters as the value is always required.\n            The parameter is available only for compatibility.\n            "
P=True
O='\n            RegEx pattern for strings.\n            '
K=bool
J=float
I=int
F=str
A=None
from typing import Any as H,Callable as Q,Dict as M,List as S,Optional as D,Sequence as z,Union as E
from annotated_doc import Doc as C
from D import params as R
from D.B import Ă
from D.N.C import Å
from typing_extensions import Annotated as B,Literal,deprecated as L
G=Ă
def ª(default:B[H,C("\n            Default value if the parameter field is not set.\n\n            This doesn't affect `Path` parameters as the value is always required.\n            The parameter is available only for compatibility.\n            ")]=...,*,default_factory:B[E[Q[[],H],A],C(T)]=G,alias:B[D[F],C(U)]=A,alias_priority:B[E[I,A],C(V)]=G,validation_alias:B[E[F,A],C(W)]=A,serialization_alias:B[E[F,A],C(X)]=A,title:B[D[F],C(Y)]=A,description:B[D[F],C(Z)]=A,gt:B[D[J],C(a)]=A,ge:B[D[J],C(b)]=A,lt:B[D[J],C(c)]=A,le:B[D[J],C(d)]=A,min_length:B[D[I],C(e)]=A,max_length:B[D[I],C(f)]=A,pattern:B[D[F],C(O)]=A,regex:B[D[F],C(O),L(g)]=A,discriminator:B[E[F,A],C(h)]=A,strict:B[E[K,A],C(i)]=G,multiple_of:B[E[J,A],C(j)]=G,allow_inf_nan:B[E[K,A],C(k)]=G,max_digits:B[E[I,A],C(l)]=G,decimal_places:B[E[I,A],C(m)]=G,examples:B[D[S[H]],C(n)]=A,example:B[D[H],L(o)]=G,openapi_examples:B[D[M[F,Å]],C(p)]=A,deprecated:B[E[L,F,K,A],C(q)]=A,include_in_schema:B[K,C(r)]=P,json_schema_extra:B[E[M[F,H],A],C(s)]=A,**D:B[H,C(t),A(u)]):A=deprecated;return R.Path(default=default,default_factory=default_factory,alias=alias,alias_priority=alias_priority,validation_alias=validation_alias,serialization_alias=serialization_alias,title=title,description=description,gt=gt,ge=ge,lt=lt,le=le,min_length=min_length,max_length=max_length,pattern=pattern,regex=regex,discriminator=discriminator,strict=strict,multiple_of=multiple_of,allow_inf_nan=allow_inf_nan,max_digits=max_digits,decimal_places=decimal_places,example=example,examples=examples,openapi_examples=openapi_examples,deprecated=A,include_in_schema=include_in_schema,json_schema_extra=json_schema_extra,**D)
def µ(default:B[H,C(v)]=Ă,*,default_factory:B[E[Q[[],H],A],C(T)]=G,alias:B[D[F],C(U)]=A,alias_priority:B[E[I,A],C(V)]=G,validation_alias:B[E[F,A],C(W)]=A,serialization_alias:B[E[F,A],C(X)]=A,title:B[D[F],C(Y)]=A,description:B[D[F],C(Z)]=A,gt:B[D[J],C(a)]=A,ge:B[D[J],C(b)]=A,lt:B[D[J],C(c)]=A,le:B[D[J],C(d)]=A,min_length:B[D[I],C(e)]=A,max_length:B[D[I],C(f)]=A,pattern:B[D[F],C(O)]=A,regex:B[D[F],C(O),L(g)]=A,discriminator:B[E[F,A],C(h)]=A,strict:B[E[K,A],C(i)]=G,multiple_of:B[E[J,A],C(j)]=G,allow_inf_nan:B[E[K,A],C(k)]=G,max_digits:B[E[I,A],C(l)]=G,decimal_places:B[E[I,A],C(m)]=G,examples:B[D[S[H]],C(n)]=A,example:B[D[H],L(o)]=G,openapi_examples:B[D[M[F,Å]],C(p)]=A,deprecated:B[E[L,F,K,A],C(q)]=A,include_in_schema:B[K,C(r)]=P,json_schema_extra:B[E[M[F,H],A],C(s)]=A,**D:B[H,C(t),A(u)]):A=deprecated;return R.Query(default=default,default_factory=default_factory,alias=alias,alias_priority=alias_priority,validation_alias=validation_alias,serialization_alias=serialization_alias,title=title,description=description,gt=gt,ge=ge,lt=lt,le=le,min_length=min_length,max_length=max_length,pattern=pattern,regex=regex,discriminator=discriminator,strict=strict,multiple_of=multiple_of,allow_inf_nan=allow_inf_nan,max_digits=max_digits,decimal_places=decimal_places,example=example,examples=examples,openapi_examples=openapi_examples,deprecated=A,include_in_schema=include_in_schema,json_schema_extra=json_schema_extra,**D)
def º(default:B[H,C(v)]=Ă,*,default_factory:B[E[Q[[],H],A],C(T)]=G,alias:B[D[F],C(U)]=A,alias_priority:B[E[I,A],C(V)]=G,validation_alias:B[E[F,A],C(W)]=A,serialization_alias:B[E[F,A],C(X)]=A,convert_underscores:B[K,C('\n            Automatically convert underscores to hyphens in the parameter field name.\n\n            Read more about it in the\n            [FastAPI docs for Header Parameters](https://fastapi.tiangolo.com/tutorial/header-params/#automatic-conversion)\n            ')]=P,title:B[D[F],C(Y)]=A,description:B[D[F],C(Z)]=A,gt:B[D[J],C(a)]=A,ge:B[D[J],C(b)]=A,lt:B[D[J],C(c)]=A,le:B[D[J],C(d)]=A,min_length:B[D[I],C(e)]=A,max_length:B[D[I],C(f)]=A,pattern:B[D[F],C(O)]=A,regex:B[D[F],C(O),L(g)]=A,discriminator:B[E[F,A],C(h)]=A,strict:B[E[K,A],C(i)]=G,multiple_of:B[E[J,A],C(j)]=G,allow_inf_nan:B[E[K,A],C(k)]=G,max_digits:B[E[I,A],C(l)]=G,decimal_places:B[E[I,A],C(m)]=G,examples:B[D[S[H]],C(n)]=A,example:B[D[H],L(o)]=G,openapi_examples:B[D[M[F,Å]],C(p)]=A,deprecated:B[E[L,F,K,A],C(q)]=A,include_in_schema:B[K,C(r)]=P,json_schema_extra:B[E[M[F,H],A],C(s)]=A,**D:B[H,C(t),A(u)]):A=deprecated;return R.Header(default=default,default_factory=default_factory,alias=alias,alias_priority=alias_priority,validation_alias=validation_alias,serialization_alias=serialization_alias,convert_underscores=convert_underscores,title=title,description=description,gt=gt,ge=ge,lt=lt,le=le,min_length=min_length,max_length=max_length,pattern=pattern,regex=regex,discriminator=discriminator,strict=strict,multiple_of=multiple_of,allow_inf_nan=allow_inf_nan,max_digits=max_digits,decimal_places=decimal_places,example=example,examples=examples,openapi_examples=openapi_examples,deprecated=A,include_in_schema=include_in_schema,json_schema_extra=json_schema_extra,**D)
def À(default:B[H,C(v)]=Ă,*,default_factory:B[E[Q[[],H],A],C(T)]=G,alias:B[D[F],C(U)]=A,alias_priority:B[E[I,A],C(V)]=G,validation_alias:B[E[F,A],C(W)]=A,serialization_alias:B[E[F,A],C(X)]=A,title:B[D[F],C(Y)]=A,description:B[D[F],C(Z)]=A,gt:B[D[J],C(a)]=A,ge:B[D[J],C(b)]=A,lt:B[D[J],C(c)]=A,le:B[D[J],C(d)]=A,min_length:B[D[I],C(e)]=A,max_length:B[D[I],C(f)]=A,pattern:B[D[F],C(O)]=A,regex:B[D[F],C(O),L(g)]=A,discriminator:B[E[F,A],C(h)]=A,strict:B[E[K,A],C(i)]=G,multiple_of:B[E[J,A],C(j)]=G,allow_inf_nan:B[E[K,A],C(k)]=G,max_digits:B[E[I,A],C(l)]=G,decimal_places:B[E[I,A],C(m)]=G,examples:B[D[S[H]],C(n)]=A,example:B[D[H],L(o)]=G,openapi_examples:B[D[M[F,Å]],C(p)]=A,deprecated:B[E[L,F,K,A],C(q)]=A,include_in_schema:B[K,C(r)]=P,json_schema_extra:B[E[M[F,H],A],C(s)]=A,**D:B[H,C(t),A(u)]):A=deprecated;return R.Cookie(default=default,default_factory=default_factory,alias=alias,alias_priority=alias_priority,validation_alias=validation_alias,serialization_alias=serialization_alias,title=title,description=description,gt=gt,ge=ge,lt=lt,le=le,min_length=min_length,max_length=max_length,pattern=pattern,regex=regex,discriminator=discriminator,strict=strict,multiple_of=multiple_of,allow_inf_nan=allow_inf_nan,max_digits=max_digits,decimal_places=decimal_places,example=example,examples=examples,openapi_examples=openapi_examples,deprecated=A,include_in_schema=include_in_schema,json_schema_extra=json_schema_extra,**D)
def Á(default:B[H,C(v)]=Ă,*,default_factory:B[E[Q[[],H],A],C(T)]=G,embed:B[E[K,A],C('\n            When `embed` is `True`, the parameter will be expected in a JSON body as a\n            key instead of being the JSON body itself.\n\n            This happens automatically when more than one `Body` parameter is declared.\n\n            Read more about it in the\n            [FastAPI docs for Body - Multiple Parameters](https://fastapi.tiangolo.com/tutorial/body-multiple-params/#embed-a-single-body-parameter).\n            ')]=A,media_type:B[F,C(w)]='application/json',alias:B[D[F],C(U)]=A,alias_priority:B[E[I,A],C(V)]=G,validation_alias:B[E[F,A],C(W)]=A,serialization_alias:B[E[F,A],C(X)]=A,title:B[D[F],C(Y)]=A,description:B[D[F],C(Z)]=A,gt:B[D[J],C(a)]=A,ge:B[D[J],C(b)]=A,lt:B[D[J],C(c)]=A,le:B[D[J],C(d)]=A,min_length:B[D[I],C(e)]=A,max_length:B[D[I],C(f)]=A,pattern:B[D[F],C(O)]=A,regex:B[D[F],C(O),L(g)]=A,discriminator:B[E[F,A],C(h)]=A,strict:B[E[K,A],C(i)]=G,multiple_of:B[E[J,A],C(j)]=G,allow_inf_nan:B[E[K,A],C(k)]=G,max_digits:B[E[I,A],C(l)]=G,decimal_places:B[E[I,A],C(m)]=G,examples:B[D[S[H]],C(n)]=A,example:B[D[H],L(o)]=G,openapi_examples:B[D[M[F,Å]],C(p)]=A,deprecated:B[E[L,F,K,A],C(q)]=A,include_in_schema:B[K,C(r)]=P,json_schema_extra:B[E[M[F,H],A],C(s)]=A,**D:B[H,C(t),A(u)]):A=deprecated;return R.Body(default=default,default_factory=default_factory,embed=embed,media_type=media_type,alias=alias,alias_priority=alias_priority,validation_alias=validation_alias,serialization_alias=serialization_alias,title=title,description=description,gt=gt,ge=ge,lt=lt,le=le,min_length=min_length,max_length=max_length,pattern=pattern,regex=regex,discriminator=discriminator,strict=strict,multiple_of=multiple_of,allow_inf_nan=allow_inf_nan,max_digits=max_digits,decimal_places=decimal_places,example=example,examples=examples,openapi_examples=openapi_examples,deprecated=A,include_in_schema=include_in_schema,json_schema_extra=json_schema_extra,**D)
def N(default:B[H,C(v)]=Ă,*,default_factory:B[E[Q[[],H],A],C(T)]=G,media_type:B[F,C(w)]='application/x-www-form-urlencoded',alias:B[D[F],C(U)]=A,alias_priority:B[E[I,A],C(V)]=G,validation_alias:B[E[F,A],C(W)]=A,serialization_alias:B[E[F,A],C(X)]=A,title:B[D[F],C(Y)]=A,description:B[D[F],C(Z)]=A,gt:B[D[J],C(a)]=A,ge:B[D[J],C(b)]=A,lt:B[D[J],C(c)]=A,le:B[D[J],C(d)]=A,min_length:B[D[I],C(e)]=A,max_length:B[D[I],C(f)]=A,pattern:B[D[F],C(O)]=A,regex:B[D[F],C(O),L(g)]=A,discriminator:B[E[F,A],C(h)]=A,strict:B[E[K,A],C(i)]=G,multiple_of:B[E[J,A],C(j)]=G,allow_inf_nan:B[E[K,A],C(k)]=G,max_digits:B[E[I,A],C(l)]=G,decimal_places:B[E[I,A],C(m)]=G,examples:B[D[S[H]],C(n)]=A,example:B[D[H],L(o)]=G,openapi_examples:B[D[M[F,Å]],C(p)]=A,deprecated:B[E[L,F,K,A],C(q)]=A,include_in_schema:B[K,C(r)]=P,json_schema_extra:B[E[M[F,H],A],C(s)]=A,**D:B[H,C(t),A(u)]):A=deprecated;return R.Form(default=default,default_factory=default_factory,media_type=media_type,alias=alias,alias_priority=alias_priority,validation_alias=validation_alias,serialization_alias=serialization_alias,title=title,description=description,gt=gt,ge=ge,lt=lt,le=le,min_length=min_length,max_length=max_length,pattern=pattern,regex=regex,discriminator=discriminator,strict=strict,multiple_of=multiple_of,allow_inf_nan=allow_inf_nan,max_digits=max_digits,decimal_places=decimal_places,example=example,examples=examples,openapi_examples=openapi_examples,deprecated=A,include_in_schema=include_in_schema,json_schema_extra=json_schema_extra,**D)
def Â(default:B[H,C(v)]=Ă,*,default_factory:B[E[Q[[],H],A],C(T)]=G,media_type:B[F,C(w)]='multipart/form-data',alias:B[D[F],C(U)]=A,alias_priority:B[E[I,A],C(V)]=G,validation_alias:B[E[F,A],C(W)]=A,serialization_alias:B[E[F,A],C(X)]=A,title:B[D[F],C(Y)]=A,description:B[D[F],C(Z)]=A,gt:B[D[J],C(a)]=A,ge:B[D[J],C(b)]=A,lt:B[D[J],C(c)]=A,le:B[D[J],C(d)]=A,min_length:B[D[I],C(e)]=A,max_length:B[D[I],C(f)]=A,pattern:B[D[F],C(O)]=A,regex:B[D[F],C(O),L(g)]=A,discriminator:B[E[F,A],C(h)]=A,strict:B[E[K,A],C(i)]=G,multiple_of:B[E[J,A],C(j)]=G,allow_inf_nan:B[E[K,A],C(k)]=G,max_digits:B[E[I,A],C(l)]=G,decimal_places:B[E[I,A],C(m)]=G,examples:B[D[S[H]],C(n)]=A,example:B[D[H],L(o)]=G,openapi_examples:B[D[M[F,Å]],C(p)]=A,deprecated:B[E[L,F,K,A],C(q)]=A,include_in_schema:B[K,C(r)]=P,json_schema_extra:B[E[M[F,H],A],C(s)]=A,**D:B[H,C(t),A(u)]):A=deprecated;return R.File(default=default,default_factory=default_factory,media_type=media_type,alias=alias,alias_priority=alias_priority,validation_alias=validation_alias,serialization_alias=serialization_alias,title=title,description=description,gt=gt,ge=ge,lt=lt,le=le,min_length=min_length,max_length=max_length,pattern=pattern,regex=regex,discriminator=discriminator,strict=strict,multiple_of=multiple_of,allow_inf_nan=allow_inf_nan,max_digits=max_digits,decimal_places=decimal_places,example=example,examples=examples,openapi_examples=openapi_examples,deprecated=A,include_in_schema=include_in_schema,json_schema_extra=json_schema_extra,**D)
def Ã(dependency:B[D[Q[...,H]],C(x)]=A,*,use_cache:B[K,C(y)]=P,scope:B[E[Literal['function','request'],A],C('\n            Mainly for dependencies with `yield`, define when the dependency function\n            should start (the code before `yield`) and when it should end (the code\n            after `yield`).\n\n            * `"function"`: start the dependency before the *path operation function*\n                that handles the request, end the dependency after the *path operation\n                function* ends, but **before** the response is sent back to the client.\n                So, the dependency function will be executed **around** the *path operation\n                **function***.\n            * `"request"`: start the dependency before the *path operation function*\n                that handles the request (similar to when using `"function"`), but end\n                **after** the response is sent back to the client. So, the dependency\n                function will be executed **around** the **request** and response cycle.\n            ')]=A):return R.Depends(dependency=dependency,use_cache=use_cache,scope=scope)
def Ä(dependency:B[D[Q[...,H]],C(x)]=A,*,scopes:B[D[z[F]],C('\n            OAuth2 scopes required for the *path operation* that uses this Security\n            dependency.\n\n            The term "scope" comes from the OAuth2 specification, it seems to be\n            intentionally vague and interpretable. It normally refers to permissions,\n            in cases to roles.\n\n            These scopes are integrated with OpenAPI (and the API docs at `/docs`).\n            So they are visible in the OpenAPI specification.\n            )\n            ')]=A,use_cache:B[K,C(y)]=P):return R.Security(dependency=dependency,scopes=scopes,use_cache=use_cache)