from enum import Enum,Flag
class i:PURE_ASCII=0;ESC_ASCII=1;HIGH_BYTE=2
class h(Flag):NONE=0;CHINESE_SIMPLIFIED=1;CHINESE_TRADITIONAL=2;JAPANESE=4;KOREAN=8;NON_CJK=16;ALL=31;CHINESE=CHINESE_SIMPLIFIED|CHINESE_TRADITIONAL;CJK=CHINESE|JAPANESE|KOREAN
class g(Enum):DETECTING=0;FOUND_IT=1;NOT_ME=2
class y:START=0;ERROR=1;ITS_ME=2
class J:
	NEGATIVE=0;UNLIKELY=1;LIKELY=2;POSITIVE=3
	@classmethod
	def get_num_categories(A):return 4
class K:UNDEFINED=255;LINE_BREAK=254;SYMBOL=253;DIGIT=252;CONTROL=251